import type { Metadata } from "next";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import { Roboto, Inter, Funnel_Sans, Nunito } from "next/font/google";
import "./globals.css";

const roboto = Roboto({
  subsets: ["latin"],
  variable: "--font-roboto",
});

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter-sans",
});

const funnelSans = Funnel_Sans({
  subsets: ["latin"],
  variable: "--font-funnel-sans",
});

const nunito = Nunito({
  subsets: ["latin"],
  variable: "--font-nunito-base",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  const topPadding = true;
  return (
    <html lang="en">
      <body
        className={`${roboto.variable} ${inter.variable} ${funnelSans.variable} ${nunito.variable} antialiased h-full font-inter`}
      >
        <Header />
        <main className={topPadding ? 'pt-16' : ''}>{children}</main>
        <Footer/>
      </body>
    </html>
  );
}
